### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by olieter** [Anders-Holst/xled_plus#26]
IndexError: tuple index out of range

**Comment by Anders-Holst** [comment]
In general, that is not a very helpful error report: You need to specify what code you tried to run, on what device and its configuration, and also provide the entire stack trace so it is possible to see on what line in what function it happens.

But let me guess, based on similar errors in he past: You have tried to use a 2-dimensional effect on a device with no layout mapping (or possibly a generation 1 device which does not reveal the layout) ? (Thus, the effect tries to access the two coordinates but there is only one coordinate available - the index along the string) If this is the case, map the leds via the app, and the effect should work.

Strictly you are right that it is a bug, or at least very asocial of the code, to just crash when this happens - it should of course write an informative message about this and silently stop. I may consider such a fix in the future.

Best
  Anders
