### ISSUE TITLE
SyntaxError: '(' was never closed

### ISSUE THREAD

**Issue by fpaniagua** [Anders-Holst/xled_plus#27]
Recently updated xled_plus, got the following error:

```shell
...
    from xled_plus.multicontrol import MultiHighControlInterface
  File "/.../site-packages/xled_plus/multicontrol.py", line 60
    self.max_movies = min([info["max_movies"] if "max_movies" in info else 15 for info in infolst]
                         ^
SyntaxError: '(' was never closed
```

https://github.com/Anders-Holst/xled_plus/blob/1123dddb2ba38ed41a6906e69230744e2e184368/xled_plus/multicontrol.py#L60

Manually adding the closing `)` seems to allow the effect to work.

**Comment by Anders-Holst** [comment]
Yes, very embarrassing, I managed to check in the wrong version of the file. Fixed now, in a new release.
